server:
  port: 8081

mvc:
  view:
    prefix: /
    suffix: .html

spring:
  profiles:
    active: dev
  application:
    name: sample-portal-yunwuye-inc-com-start
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

  dubbo:
   application:
    name: consumer
   registry:
    address: zookeeper://127.0.0.1:2181
    packageName: com.yunwuye.sample.service.impl
   timeout: 3000
   protocol:
    name: dubbo
    #host: 192.168.3.50
    port: 20881
   consumer:
     #filter: catTransaction
     check: false
    #consumer:
    #check: false
    #reference:
    #loadbalance: roundrobin
   scan: com.yunwuye.sample.service.impl

jwt:
  prefix: Bearer 
  header: JWT_TOKEN
  # This token must be encoded using Base64 with mininum 88 Bits (you can type ` openssl enc -base64 <<< 'Authorization' or openssl enc -base64 -d <<< QXV0aG9yaXphdGlvbgo= ` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 24 hours 86400
  token-validity-in-seconds: 600
  # valid 30 hours 108000
  token-validity-in-seconds-for-remember-me: 100
  route:
    authentication:
      path: auth
      refresh: refresh

cross:
  url:
    regx: '*yuwuye.(com|net|test)'
